package main;

public enum TokenType {
    RESERVED_WORD,
    KEYWORD,
    SYMBOL,
    NUMERICAL,
    LITERAL,
    LOGICAL_OPERATOR,
    RELATIONAL_OPERATOR,
    ARITHMETIC_OPERATOR,
    IDENTIFIER;
}
