package main;

public enum TokenType {
    RESERVED_WORD,
    NUMERICAL,
    LITERAL,
    LOGICAL_OPERATOR,
    RELATIONAL_OPERATOR,
    ARITHMETIC_OPERATOR,
    IDENTIFIER,
    COMMA,
    SEMICOLON,
    EQUAL,
    L_PAREN,
    R_PAREN,
    L_BRACKET,
    R_BRACKET,
    SHARP;
}
